### ISSUE TITLE
Caused by: org.apache.commons.configuration.ConversionException: 'connections.connection(0).peerport' doesn't map to an Integer object

### ISSUE THREAD

**Issue by AShabana** [RestComm/Restcomm-Docker#111]
Dears , when we add smpp configuration to our docker file as below
`
RCBCONF_SMPP_ACTIVATE=true
GENERIC_SMPP_ID=xxxxx
GENERIC_SMPP_PASSWORD=xxxxxxx
GENERIC_SMPP_SYSTEM_TYPE=xxxxx
GENERIC_SMPP_PEER_IP=xx.xxxxx.xx
GENERIC_SMPP_PEER_PORT=08000
`

restcomm docker enter infinit loop , seem it not able to parse port 

and it throw the below exception
`restcomm.connect.commons.faulttolerance.RestcommSupervisorStrategy] (RestComm-akka.actor.default-dispatcher-6) RestcommSupervisorStrategy, actor exception handling. Actor path akka://RestComm/user/$f, exception cause 6750498e-9c18-4cf3-b7e6-3b1784e4dfb6akka.actor.ActorInitializationException: exception during creation, default exception handling strategy Resume
restcomm_1  | 16:21:25,361 ERROR [org.restcomm.connect.commons.faulttolerance.RestcommSupervisorStrategy] (RestComm-akka.actor.default-dispatcher-6) RestcommSupervisorStrategy, actor exception handling. Actor path akka://RestComm/user/$f, exception cause 47987640-8b7f-4fc9-8cee-2322365e5980akka.actor.ActorInitializationException: exception during creation, default exception handling strategy Resume
restcomm_1  | 16:21:25,356 ERROR [akka.actor.ActorCell] (RestComm-akka.actor.default-dispatcher-8) changing Resume into Create after 78bc1997-49e9-481e-9d11-4176ac6111dcakka.actor.ActorInitializationException: exception during creation
restcomm_1  | 16:21:25,362 ERROR [org.restcomm.connect.commons.faulttolerance.RestcommSupervisorStrategy] (RestComm-akka.actor.default-dispatcher-5) RestcommSupervisorStrategy, actor exception handling. Actor path akka://RestComm/user/$f, exception cause 04a3b116-5ce5-4f13-949f-1e1e779a950fakka.actor.ActorInitializationException: exception during creation, default exception handling strategy Resume
restcomm_1  | 16:21:25,363 ERROR [org.restcomm.connect.commons.faulttolerance.RestcommSupervisorStrategy] (RestComm-akka.actor.default-dispatcher-5) RestcommSupervisorStrategy, actor exception handling. Actor path akka://RestComm/user/$f, exception cause 0b8a69b1-7283-4362-ace6-dc698b964ecfakka.actor.ActorInitializationException: exception during creation, default exception handling strategy Resume
restcomm_1  | 16:21:25,364 ERROR [org.restcomm.connect.commons.faulttolerance.RestcommSupervisorStrategy] (RestComm-akka.actor.default-dispatcher-5) RestcommSupervisorStrategy, actor exception handling. Actor path akka://RestComm/user/$f, exception cause 0595f45f-e24d-44cd-b82d-6f02d50f690aakka.actor.ActorInitializationException: exception during creation, default exception handling strategy Resume
restcomm_1  | 16:21:25,361 ERROR [akka.actor.ActorCell] (RestComm-akka.actor.default-dispatcher-8) error while processing Resume(78bc1997-49e9-481e-9d11-4176ac6111dcakka.actor.ActorInitializationException: exception during creation): 607532ff-6ac6-4924-8c47-142df744aa8cakka.actor.ActorInitializationException: exception during creation
restcomm_1  |   at akka.actor.ActorInitializationException$.apply(Actor.scala:170) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   at akka.actor.ActorCell.create(ActorCell.scala:496) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   at akka.actor.dungeon.FaultHandling$class.finishCreate(FaultHandling.scala:137) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   at akka.actor.dungeon.FaultHandling$class.faultCreate(FaultHandling.scala:131) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   at akka.actor.ActorCell.faultCreate(ActorCell.scala:306) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   at akka.actor.dungeon.FaultHandling$class.faultResume(FaultHandling.scala:103) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   at akka.actor.ActorCell.faultResume(ActorCell.scala:306) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   at akka.actor.ActorCell.systemInvoke(ActorCell.scala:366) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:256) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   at akka.dispatch.Mailbox.run(Mailbox.scala:211) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
restcomm_1  |   at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
restcomm_1  |   at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
restcomm_1  |   at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
restcomm_1  | Caused by: org.apache.commons.configuration.ConversionException: 'connections.connection(0).peerport' doesn't map to an Integer object
restcomm_1  |   at org.apache.commons.configuration.AbstractConfiguration.getInteger(AbstractConfiguration.java:854) [commons-configuration-1.7.jar:1.7]
restcomm_1  |   at org.apache.commons.configuration.AbstractConfiguration.getInt(AbstractConfiguration.java:815) [commons-configuration-1.7.jar:1.7]
restcomm_1  |   at org.restcomm.connect.sms.smpp.SmppService.initializeSmppConnections(SmppService.java:134) [restcomm-connect.sms-8.2.0.1240.jar:8.2.0.1240]
restcomm_1  |   at org.restcomm.connect.sms.smpp.SmppService.<init>(SmppService.java:107) [restcomm-connect.sms-8.2.0.1240.jar:8.2.0.1240]
restcomm_1  |   at org.restcomm.connect.sms.SmsServiceProxy$2.create(SmsServiceProxy.java:89) [restcomm-connect.sms-8.2.0.1240.jar:8.2.0.1240]
restcomm_1  |   at org.restcomm.connect.sms.SmsServiceProxy$2.create(SmsServiceProxy.java:85) [restcomm-connect.sms-8.2.0.1240.jar:8.2.0.1240]
restcomm_1  |   at akka.actor.Props$$anonfun$$init$$1.apply(Props.scala:129) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   at akka.actor.Props$$anonfun$$init$$1.apply(Props.scala:129) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   at akka.actor.ActorCell.newActor(ActorCell.scala:461) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   at akka.actor.ActorCell.create(ActorCell.scala:479) [akka-actor_2.10-2.1.2.jar:]
restcomm_1  |   ... 13 more
restcomm_1  | Caused by: org.apache.commons.configuration.ConversionException: Could not convert  to java.lang.Integer
restcomm_1  |   at org.apache.commons.configuration.PropertyConverter.toNumber(PropertyConverter.java:413) [commons-configuration-1.7.jar:1.7]
restcomm_1  |   at org.apache.commons.configuration.PropertyConverter.toInteger(PropertyConverter.java:260) [commons-configuration-1.7.jar:1.7]
restcomm_1  |   at org.apache.commons.configuration.AbstractConfiguration.getInteger(AbstractConfiguration.java:850) [commons-configuration-1.7.jar:1.7]
restcomm_1  |   ... 22 more
restcomm_1  | Caused by: java.lang.NumberFormatException: For input string: ""
restcomm_1  |   at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) [rt.jar:1.7.0_95]
`
please advice

**Comment by AShabana** [comment]
Seem this is a bug in the parser , or format of the paramter has been changed from the previous release 

I iterated in the env. file with 

RCBCONF_SMPP_SYSTEM_ID
RCBCONF_SMPP_PASSWORD
RCBCONF_SMPP_SYSTEM_TYPE
RCBCONF_SMPP_PEER_IP
RCBCONF_SMPP_PEER_PORT


and it worked

**Comment by AShabana** [comment]
anyway hope you update the documentation , or refer to the new one if you plan to have more customers with production deployments
