### ISSUE TITLE
Can't login to Olympus but the administration console is fine

### ISSUE THREAD

**Issue by pouraghajanOldAcc** [RestComm/Restcomm-Docker#117]
Hi,

I've gone through all the steps mentioned in RestComm Docker quick start guide at [http://documentation.telestax.com/connect/configuration/docker/Restcomm%20-%20Docker%20Quick%20Start%20Guide.html](url) but there is a problem I couldn't solve.
After deploying the container using `docker-composer up` command the Olympus console gets open in the browser but I can't login. (at the same time the administration console at [http://mylocalip:8443](url) is accessible and I can login to it using the default user/pass).
Here is the output of ipconfig command on my Windows 10 command prompt:
![image](https://user-images.githubusercontent.com/6200346/34329781-d3258c3a-e904-11e7-9c00-e3ec1066f047.png)

and this is the IP config I've put in docker-compose.yml file:
`RCBCONF_STATIC_ADDRESS: 192.168.1.8   # YOUR LOCAL IP ADDRESS GOES HERE.`

BTW, consider below points in my case:

- Windows Firewall is disabled
- I have tested in "Google Chrome", "Mozilla FireFox" and "Microsoft Edge" and the result was all the same.
- I have enabled and used 8080 port uncommenting the related line in docker-compose.yml file to exclude the effects of self signed certificate potential issues.
- When I hit the Login button in Olympus login page, no log (neither any action) appears in the docker output stream in my PowerShell console. (it seems the request never reaches to RestComm's JBoss server)
- Making sure to capture all possible logs I've set them all to DEBUG level.

**Comment by pouraghajanOldAcc** [comment]
In addition to that, I'm getting below error in FireFox Web Developer console:

2017-25-12 12:09:35.362 ERROR Error: $scope.iceServers is undefined
$scope.connect@https://192.168.1.8:8443/olympus/resources/js/controllers/sign-in.js:130:9
$parseFunctionCall@https://192.168.1.8:8443/olympus/lib/angular/angular.js:12336:15
callback@https://192.168.1.8:8443/olympus/lib/angular/angular.js:21422:17
$eval@https://192.168.1.8:8443/olympus/lib/angular/angular.js:14388:16
$apply@https://192.168.1.8:8443/olympus/lib/angular/angular.js:14487:18
ngEventHandler/<@https://192.168.1.8:8443/olympus/lib/angular/angular.js:21427:17
dispatch@https://192.168.1.8:8443/olympus/lib/jquery/dist/jquery.js:4429:15
add/elemData.handle@https://192.168.1.8:8443/olympus/lib/jquery/dist/jquery.js:4116:6
 

Stack trace: 
	commonLog@https://192.168.1.8:8443/olympus/resources/js/mobicents-libs/WebRTComm.js:4872:10
	console.error@https://192.168.1.8:8443/olympus/resources/js/mobicents-libs/WebRTComm.js:4945:4
	consoleLog/<@https://192.168.1.8:8443/olympus/lib/angular/angular.js:11598:18
	$ExceptionHandlerProvider/this.$get</<@https://192.168.1.8:8443/olympus/lib/angular/angular.js:8548:7
	$apply@https://192.168.1.8:8443/olympus/lib/angular/angular.js:14489:11
	ngEventHandler/<@https://192.168.1.8:8443/olympus/lib/angular/angular.js:21427:17
	dispatch@https://192.168.1.8:8443/olympus/lib/jquery/dist/jquery.js:4429:15
	add/elemData.handle@https://192.168.1.8:8443/olympus/lib/jquery/dist/jquery.js:4116:6

The same error in Chrome:

2017-25-12 12:00:36.868 ERROR TypeError: Cannot read property 'iceServers' of undefined
    at ChildScope.$scope.connect (http://192.168.1.8:8080/olympus/resources/js/controllers/sign-in.js:130:39)
    at $parseFunctionCall (http://192.168.1.8:8080/olympus/lib/angular/angular.js:12336:18)
    at callback (http://192.168.1.8:8080/olympus/lib/angular/angular.js:21422:17)
    at ChildScope.$eval (http://192.168.1.8:8080/olympus/lib/angular/angular.js:14388:28)
    at ChildScope.$apply (http://192.168.1.8:8080/olympus/lib/angular/angular.js:14487:23)
    at HTMLButtonElement.<anonymous> (http://192.168.1.8:8080/olympus/lib/angular/angular.js:21427:23)
    at HTMLButtonElement.dispatch (http://192.168.1.8:8080/olympus/lib/jquery/dist/jquery.js:4430:9)
    at HTMLButtonElement.elemData.handle (http://192.168.1.8:8080/olympus/lib/jquery/dist/jquery.js:4116:28) 

Stack trace: 
    at commonLog (http://192.168.1.8:8080/olympus/resources/js/mobicents-libs/WebRTComm.js:4872:10)
    at console.error (http://192.168.1.8:8080/olympus/resources/js/mobicents-libs/WebRTComm.js:4945:4)
    at Object.error (http://192.168.1.8:8080/olympus/lib/angular/angular.js:11598:24)
    at http://192.168.1.8:8080/olympus/lib/angular/angular.js:8548:18
    at ChildScope.$apply (http://192.168.1.8:8080/olympus/lib/angular/angular.js:14489:11)
    at HTMLButtonElement.<anonymous> (http://192.168.1.8:8080/olympus/lib/angular/angular.js:21427:23)
    at HTMLButtonElement.dispatch (http://192.168.1.8:8080/olympus/lib/jquery/dist/jquery.js:4430:9)
    at HTMLButtonElement.elemData.handle (http://192.168.1.8:8080/olympus/lib/jquery/dist/jquery.js:4116:28)

Also pausing the script at the point on which the exception has been thrown, in Chrome developer console, I've found below error (hope it could help):

![image](https://user-images.githubusercontent.com/6200346/34357732-ca4b6520-ea5e-11e7-864a-44c8234f3e3e.png)

**Comment by pouraghajanOldAcc** [comment]
Figured it out, I have ran the ResComm on a virtual machine while my host OS wasn't connected to Internet (didn't have full access as a matter of fact ;) ).
It seems during the startup, RestComm does some transactions with external services over the Internet (Don't know why, btw)!!
As soon as I connected my host OS to the Internet, problem solved.

**Comment by gsaslis** [comment]
Thanks for reporting back @pouraghajan !

Yes, I can confirm internet connectivity is required, both for some tools which are used at first run, but also for some runtime dependencies. For anyone else who comes across this, please ensure you have a working internet connection
