### ISSUE TITLE
Issue on port forwarding for HTTPS (443)

### ISSUE THREAD

**Issue by ibstelix** [RestComm/Restcomm-Docker#37]
Hi,
using port forwarding for HTTPS (with any other port number than 443) make impossible to connect to RVD.
the traffic is seen as plaintext instead of ssl traffic.
The error message in the logs is as follows:
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
    at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:671) [jsse.jar:1.7.0_80]
    at sun.security.ssl.InputRecord.read(InputRecord.java:504) [jsse.jar:1.7.0_80]
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:934) [jsse.jar:1.7.0_80]
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332) [jsse.jar:1.7.0_80]
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359) [jsse.jar:1.7.0_80]
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343) [jsse.jar:1.7.0_80]
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)

**Comment by leftyb** [comment]
Fixed. #38
